version: '3'
services:
        ansible:
               container_name: ansible
               image: ansible
               tty: true
               stdin_open: true
               build:
                    context: ./
               networks:
                       - net
        remote_host:
               container_name: remote-host
               image: remote-host-ssh
               build:
                    context: ./client
               networks:
                       - net
networks:
        net:
