name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Docker login
      env:
           DOCKER_USERNAME =${{ secrets.DOCKER_USERNSAME }}
           DOCKER_PASSWORD =${{ secrets.DOCKER_PASSWORD }}
      run: |
           docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      
    - name: Build the master image
      run: |
          docker build . --file Dockerfile --tag ansible:$(date +%s)
    - name: Build the client image
      run: |
          docker build ./client --file Dockerfile --tag remote-host-ssh:$(date +%s)
          
      
