name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Docker login
      env: 
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
          
    - name: Build the master image
      run: |
          docker build . --file Dockerfile --tag ansible:v1.0
          
    - name: Build the client image
      run: |
          docker build ./client --file Dockerfile --tag remote-host-ssh:V1.0
          
    - name: Docker image push in DockerHub
      run: |
           docker push ansible:v1.0
           docker push remote-host-ssh:V1.0
          
      
